<a href="https://colab.research.google.com/github/AbdulRahim96/AI-Lab/blob/main/lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab task

In [2]:
import numpy as np

maxDimension = 8

array = np.ones((maxDimension,maxDimension)) # all 1s
array[1 : maxDimension-1 , 1 : maxDimension-1] = 0 # neglecting 1st : last rows , neglecting 1st : last columns

print(array)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


# Post Lab Task

In [3]:
import numpy as np

dimensions = 8
ar1 = np.ones((dimensions,dimensions))
ar1[: :2, : :2] = 0 # even number of rows
ar1[1: :2, 1: :2] = 0 # odd number of rows
print(ar1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
