Graph Algorithm

In [1]:
Graph_nodes = {
    'A': [('B', 6), ('F', 3)],
    'B': [('A', 6), ('C', 3), ('D', 2)],
    'C': [('B', 3), ('D', 1), ('E', 5)],
    'D': [('B', 2), ('C', 1), ('E', 8)],
    'E': [('C', 5), ('D', 8), ('I', 5), ('J', 5)],
    'F': [('A', 3), ('G', 1), ('H', 7)],
    'G': [('F', 1), ('I', 3)],
    'H': [('F', 7), ('I', 2)],
    'I': [('E', 5), ('G', 3), ('H', 2), ('J', 3)],
    'J': [('E', 5), ('I', 3)]
}


def Heuristic(n): # where n is the key
    H = {
        'A': 10,
        'B': 8,
        'C': 5,
        'D': 7,
        'E': 3,
        'F': 6,
        'G': 5,
        'H': 3,
        'I': 1,
        'J': 0
    }

    return H[n] # return value using key

#define fuction to return neighbor and its distance
#from the passed node
def get_neighbors(v):
    if v in Graph_nodes:
        return Graph_nodes[v]
    else:
        return None
    
def aStarAlgo(start_node, stop_node):
         
        open_set = set(start_node) 
        closed_set = set()
        g = {} #store distance from starting node
        parents = {}# parents contains an adjacency map of all nodes
 
        #ditance of starting node from itself is zero
        g[start_node] = 0
        
        #so start_node is set to none
        parents[start_node] = None
         
         
        while len(open_set) > 0:
            n = None
            
            #node with lowest f() is found
            for v in open_set:
                if n == None or g[v] + Heuristic(v) < g[n] + Heuristic(n):
                    n = v
             
                     
            if n == stop_node or Graph_nodes[n] == None:
                pass
            else:
                
                for (m, weight) in get_neighbors(n):
                    #nodes 'm' not in first and last set are added to first
                    #n is set its parent
                    if m not in open_set and m not in closed_set:
                        open_set.add(m)
                        parents[m] = n
                        g[m] = g[n] + weight
                         
     
                    #for each node m,compare its distance from start i.e g(m) to the
                    #from start through n node
                    else:
                        
                        if g[m] > g[n] + weight:
                            #update g(m)
                            g[m] = g[n] + weight
                            #change parent of m to n
                            parents[m] = n
                             
                            #if m in closed set,remove and add to open
                            if m in closed_set:
                                closed_set.remove(m)
                                open_set.add(m)
 
            if n == None:
                print('Path does not exist!')
                return None
 
            # if the current node is the stop_node
            # then we begin reconstructin the path from it to the start_node
            if n == stop_node:
                path = []
 
                while parents[n] != None: #parent of 'A' is 'null'
                    print("Parent of",n , "is", parents[n])
                    path.append(n)
                    print("append", path)
                    n = parents[n]
 
                path.append(start_node)
                print("append", path)
                path.reverse()
 
                print('Path found: {}'.format(path))
                return path
 
 
            # remove n from the open_list, and add it to closed_list
            # because all of his neighbors were inspected
            open_set.remove(n)
            closed_set.add(n)
 
        print('Path does not exist!')
        return None

mypath = aStarAlgo('A', 'J')
#print(mypath[ : : 2])

Parent of J is I
append ['J']
Parent of I is G
append ['J', 'I']
Parent of G is F
append ['J', 'I', 'G']
Parent of F is A
append ['J', 'I', 'G', 'F']
append ['J', 'I', 'G', 'F', 'A']
Path found: ['A', 'F', 'G', 'I', 'J']


Matrix

In [4]:
import numpy as np
import heapq

# Initial matrix setup
array = np.ones((5, 5))
array[1:4, 1:2] = 0
array[1][2] = 0 #0 means blocked path
array[1][3] = 5 #5 means goal point
array[4][0] = 4 #4 means start point

# Print initial matrix
print("Initial matrix:")
print(array)

# Heuristic function (Manhattan distance)
def Heuristic(n, goal):
    return abs(n[0] - goal[0]) + abs(n[1] - goal[1])

# Get neighbors function
def get_neighbors(n, array):
    neighbors = []
    for direction in [(0, 1), (1, 0), (0, -1), (-1, 0)]:
        neighbor = (n[0] + direction[0], n[1] + direction[1])
        if 0 <= neighbor[0] < array.shape[0] and 0 <= neighbor[1] < array.shape[1]:
            if array[neighbor] != 0:
                neighbors.append((neighbor, 1))
    return neighbors

# A* Algorithm implementation
def aStarAlgo(start_node, stop_node, array):
    open_set = set([start_node])
    closed_set = set()
    g = {start_node: 0}
    parents = {start_node: None}

    while len(open_set) > 0:
        n = None
        
        # Node with the lowest f() is found
        for v in open_set:
            if n is None or g[v] + Heuristic(v, stop_node) < g[n] + Heuristic(n, stop_node):
                n = v

        if n is None:
            print('Path does not exist!')
            return None

        if n == stop_node:
            path = []
            while parents[n] is not None:
                path.append(n)
                n = parents[n]
            path.append(start_node)
            path.reverse()
            # Update the matrix with the path
            for position in path:
                if array[position] == 1:
                    array[position] = 2 #2 is the path from start to end
            return path

        for (m, weight) in get_neighbors(n, array):
            if m not in open_set and m not in closed_set:
                open_set.add(m)
                parents[m] = n
                g[m] = g[n] + weight
            else:
                if g[m] > g[n] + weight:
                    g[m] = g[n] + weight
                    parents[m] = n
                    if m in closed_set:
                        closed_set.remove(m)
                        open_set.add(m)

        
        open_set.remove(n)
        closed_set.add(n)

    print('Path does not exist!')
    return None

# Define start and goal positions
start = (4, 0)
goal = (1, 3)

# Find path
path = aStarAlgo(start, goal, array)



# Print the updated matrix
print("\nMatrix after finding the path:")
print(array)


Initial matrix:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 5. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [4. 1. 1. 1. 1.]]

Matrix after finding the path:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 5. 1.]
 [1. 0. 1. 2. 1.]
 [1. 0. 1. 2. 1.]
 [4. 2. 2. 2. 1.]]
